# see: https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options
# see: https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#configuration
# see: https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#usage

call_parentheses = "Always"
collapse_simple_statement = "Always"
column_width = 130
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = true
